#!/bin/bash
# make sure about my position
cd $(dirname $0)

# just to have notion
date "+%d/%m/%Y %T"

# source openfoam run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Clear old IC
rm -rf 0

# create base mesh 
runApplication blockMesh

# generate lambda field
runApplication createLambdaPipeV1 0.7

# create new patch from boundary faces inside lambda
runApplication createPatch -overwrite -dict system/createPatchDictNewPatch

# correct the lambda field based on the new boundary
python rewriteLambdaBoundary.py
runApplication correctLambdaBoundary

# create files for postprocessing
paraFoam -touch

# run checkMesh
runApplication checkMesh -allGeometry -allTopology

# copy IC
mkdir -p 0
cp -rf 0.org/* 0
