#!/bin/bash

cwd=$(echo $PWD)

cd $cwd/src/HFDIBRANS
./Allwclean

cd $cwd/src/HFDIBMomentumTransportModels/momentumTransportModels
./Allwclean

cd $cwd/src/HFDIBMomentumTransportModels/incompressible
./Allwclean

cd $cwd/applications/solvers/simpleHFDIBRANSFoam
./Allwclean

cd $cwd/applications/solvers/scalarHFDIBTransportFoam
./Allwclean

cd $cwd
