#!/bin/bash

cwd=$(echo $PWD)

cd $cwd/src/HFDIBRANS
./Allwmake

cd $cwd/src/HFDIBTurbulenceModels/turbulenceModels
./Allwmake

cd $cwd/src/HFDIBTurbulenceModels/incompressible
./Allwmake

cd $cwd/applications/solvers/simpleHFDIBRANSFoam
./Allwmake

cd $cwd
