#!/bin/bash

cwd=$(echo $PWD)

cd $cwd/src/HFDIBRANS
./Allwclean

cd $cwd/src/HFDIBTurbulenceModels/turbulenceModels
./Allwclean

cd $cwd/src/HFDIBTurbulenceModels/incompressible
./Allwclean

cd $cwd/applications/solvers/simpleHFDIBRANSFoam
./Allwclean

cd $cwd/applications/solvers/buoyantBoussinesqSimpleHFDIBRANSFoam
./Allwclean

cd $cwd/applications/solvers/scalarHFDIBTransportFoam
./Allwclean

cd $cwd
