#!/bin/bash

cwd=$(echo $PWD)

cd $cwd/src/HFDIBRANS
./Allwmake

cd $cwd/src/HFDIBMomentumTransportModels/momentumTransportModels
./Allwmake

cd $cwd/src/HFDIBMomentumTransportModels/incompressible
./Allwmake

cd $cwd/applications/solvers/simpleHFDIBRANSFoam
./Allwmake

cd $cwd
