#!/bin/bash

cwd=$(echo $PWD)

cd $cwd/straightPipe/openHFDIBRANS
./Allclean

cd $cwd/straightPipe/simpleFoam
./Allclean

cd $cwd/straightPipe/laminar_openHFDIBRANS
./Allclean

cd $cwd/straightPipe/laminar_simpleFoam
./Allclean

cd $cwd/asymmetricalPipe/openHFDIBRANS
./Allclean

cd $cwd/asymmetricalPipe/simpleFoam
./Allclean

cd $cwd/backwardFacingStep/openHFDIBRANS
./Allclean

cd $cwd/backwardFacingStep/simpleFoam
./Allclean

cd $cwd
