#!/bin/bash

cwd=$(echo $PWD)

cd $cwd/straightPipe/openHFDIBRANS
./Allrun

cd $cwd/straightPipe/simpleFoam
./Allrun

cd $cwd/asymmetricalPipe/openHFDIBRANS
./Allrun

cd $cwd/asymmetricalPipe/simpleFoam
./Allrun

cd $cwd
