#!/bin/bash

cwd=$(echo $PWD)

cd $cwd/straightPipe/openHFDIBRANS
./Allrun

cd $cwd/straightPipe/simpleFoam
./Allrun

cd $cwd/straightPipe/laminar_openHFDIBRANS
./Allrun

cd $cwd/straightPipe/laminar_simpleFoam
./Allrun

cd $cwd/asymmetricalPipe/openHFDIBRANS
./Allrun

cd $cwd/asymmetricalPipe/simpleFoam
./Allrun

cd $cwd/backwardFacingStep/openHFDIBRANS
./Allrun

cd $cwd/backwardFacingStep/simpleFoam
./Allrun

cd $cwd
