#!/bin/bash
# set openFoam environment
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Clear old IC
rm -rf 0

# create base mesh 
runApplication blockMesh

# copy IC
mkdir -p 0
cp -rf 0.org/* 0

# create files for postprocessing
paraFoam -touch

# decompose
runApplication decomposePar

# get the solver application
application=`getApplication`

# run the application
runParallel $application

# reconstruct
runApplication reconstructPar -newTimes
